//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.UI.Properties.Resour" +
                            "ces", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationEventLog {
            get {
                return ResourceManager.GetString("ApplicationEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Server SMART 24/7.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bar_icon_delete_red {
            get {
                object obj = ResourceManager.GetObject("bar_icon_delete_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BitLocker48 {
            get {
                object obj = ResourceManager.GetObject("BitLocker48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_Gradient {
            get {
                object obj = ResourceManager.GetObject("Blue_Gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cert16 {
            get {
                object obj = ResourceManager.GetObject("Cert16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Change {
            get {
                object obj = ResourceManager.GetObject("Change", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all configuration values to their defaults?.
        /// </summary>
        internal static string ConfirmResetDefaults {
            get {
                return ResourceManager.GetString("ConfirmResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 24/7 Dojo North Software.
        /// </summary>
        internal static string CopyrightBanner {
            get {
                return ResourceManager.GetString("CopyrightBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CrackedGlassThumb {
            get {
                object obj = ResourceManager.GetObject("CrackedGlassThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Critical16 {
            get {
                object obj = ResourceManager.GetObject("Critical16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Decrypt48 {
            get {
                object obj = ResourceManager.GetObject("Decrypt48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated in Memory of Joseph B. Sawyer.
        /// </summary>
        internal static string DedicationBanner {
            get {
                return ResourceManager.GetString("DedicationBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DiskHeartBeat48x48 {
            get {
                object obj = ResourceManager.GetObject("DiskHeartBeat48x48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveBender.
        /// </summary>
        internal static string DiskPoolProviderDriveBender {
            get {
                return ResourceManager.GetString("DiskPoolProviderDriveBender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrivePoolService.
        /// </summary>
        internal static string DiskPoolProviderDrivePool {
            get {
                return ResourceManager.GetString("DiskPoolProviderDrivePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DriveBender16 {
            get {
                object obj = ResourceManager.GetObject("DriveBender16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string DriveLetterNa {
            get {
                return ResourceManager.GetString("DriveLetterNa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Email32 {
            get {
                object obj = ResourceManager.GetObject("Email32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Encrypt48 {
            get {
                object obj = ResourceManager.GetObject("Encrypt48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected disk is no longer available. Click &quot;Refresh Disks&quot; to get the current list of available disks..
        /// </summary>
        internal static string ErrorMessageDiskNotAvailable {
            get {
                return ResourceManager.GetString("ErrorMessageDiskNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceptions were detected: .
        /// </summary>
        internal static string ErrorMessageGeneral {
            get {
                return ResourceManager.GetString("ErrorMessageGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email configuration is invalid. Email alerts will not be available until your email settings are corrected..
        /// </summary>
        internal static string ErrorMessageInvalidEmailConfig {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidEmailConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings occurred reading data from the Registry. Unreadable values have been reset to their defaults..
        /// </summary>
        internal static string ErrorMessageRegistryReadsFailedWarn {
            get {
                return ResourceManager.GetString("ErrorMessageRegistryReadsFailedWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the Registry. .
        /// </summary>
        internal static string ErrorMessageRegistryWriteFailed {
            get {
                return ResourceManager.GetString("ErrorMessageRegistryWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Not Available.
        /// </summary>
        internal static string ErrorMessageTitleDiskNotAvailable {
            get {
                return ResourceManager.GetString("ErrorMessageTitleDiskNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Configuration.
        /// </summary>
        internal static string ErrorMessageTitleInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorMessageTitleInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe.
        /// </summary>
        internal static string ErrorMessageTitleSevere {
            get {
                return ResourceManager.GetString("ErrorMessageTitleSevere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start worker process: .
        /// </summary>
        internal static string ErrorMessageWorkerProcessStartFail {
            get {
                return ResourceManager.GetString("ErrorMessageWorkerProcessStartFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI worker process encountered an exception: .
        /// </summary>
        internal static string ErrorMessageWorkerProcessWmiFail {
            get {
                return ResourceManager.GetString("ErrorMessageWorkerProcessWmiFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the disks in your Server are exposing SMART data via WMI. Display of SMART data or analysis is not available for all non-USB disks. SMART data for USB disks may still be available..
        /// </summary>
        internal static string ErrorMessageWorkerProcessWmiNotSupported {
            get {
                return ResourceManager.GetString("ErrorMessageWorkerProcessWmiNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSMART-E.
        /// </summary>
        internal static string EventLogJoshua {
            get {
                return ResourceManager.GetString("EventLogJoshua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSMART-W.
        /// </summary>
        internal static string EventLogTaryn {
            get {
                return ResourceManager.GetString("EventLogTaryn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exclamation48 {
            get {
                object obj = ResourceManager.GetObject("Exclamation48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FlashDrive48 {
            get {
                object obj = ResourceManager.GetObject("FlashDrive48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Green_Gradient {
            get {
                object obj = ResourceManager.GetObject("Green_Gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hard_drive_repair_16 {
            get {
                object obj = ResourceManager.GetObject("hard_drive_repair_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Healthy16 {
            get {
                object obj = ResourceManager.GetObject("Healthy16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help16 {
            get {
                object obj = ResourceManager.GetObject("Help16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help48 {
            get {
                object obj = ResourceManager.GetObject("Help48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HunkaHunkaMcBabyMcOrneryMcSlabMcHandsomeMcBabyMcGoodLookingMcSlabMcFlawlessMcSlabMcBaby {
            get {
                object obj = ResourceManager.GetObject("HunkaHunkaMcBabyMcOrneryMcSlabMcHandsomeMcBabyMcGoodLookingMcSlabMcFlawlessMcSlab" +
                        "McBaby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ignore16 {
            get {
                object obj = ResourceManager.GetObject("Ignore16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IgnoreProblem48 {
            get {
                object obj = ResourceManager.GetObject("IgnoreProblem48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information16 {
            get {
                object obj = ResourceManager.GetObject("Information16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keyboard16 {
            get {
                object obj = ResourceManager.GetObject("Keyboard16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keyboard32 {
            get {
                object obj = ResourceManager.GetObject("Keyboard32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Keyboard48 {
            get {
                object obj = ResourceManager.GetObject("Keyboard48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LightningThumb {
            get {
                object obj = ResourceManager.GetObject("LightningThumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lock24 {
            get {
                object obj = ResourceManager.GetObject("Lock24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sil.
        /// </summary>
        internal static string LogfileExtension {
            get {
                return ResourceManager.GetString("LogfileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HssUiLog_.
        /// </summary>
        internal static string LogfilePrefix {
            get {
                return ResourceManager.GetString("LogfilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MetalGrate {
            get {
                object obj = ResourceManager.GetObject("MetalGrate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifyMyAndroid32 {
            get {
                object obj = ResourceManager.GetObject("NotifyMyAndroid32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Policy {
            get {
                object obj = ResourceManager.GetObject("Policy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PolicyWithToolbox {
            get {
                object obj = ResourceManager.GetObject("PolicyWithToolbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Prowl32 {
            get {
                object obj = ResourceManager.GetObject("Prowl32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reboot16 {
            get {
                object obj = ResourceManager.GetObject("Reboot16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RefreshDisk24 {
            get {
                object obj = ResourceManager.GetObject("RefreshDisk24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationEnabled.
        /// </summary>
        internal static string RegistryConfigAuthenticationEnabled {
            get {
                return ResourceManager.GetString("RegistryConfigAuthenticationEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Dojo North Software\Taryn BitLocker Manager.
        /// </summary>
        internal static string RegistryConfigBaronessTbm {
            get {
                return ResourceManager.GetString("RegistryConfigBaronessTbm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideBitLockerTab.
        /// </summary>
        internal static string RegistryConfigBitLockerHideTab {
            get {
                return ResourceManager.GetString("RegistryConfigBitLockerHideTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitLockerPreventLocking.
        /// </summary>
        internal static string RegistryConfigBitLockerPreventLocking {
            get {
                return ResourceManager.GetString("RegistryConfigBitLockerPreventLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BitLockerShowAllDrives.
        /// </summary>
        internal static string RegistryConfigBitLockerShowAllDrives {
            get {
                return ResourceManager.GetString("RegistryConfigBitLockerShowAllDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriticalTempThreshold.
        /// </summary>
        internal static string RegistryConfigCriticalTempThreshold {
            get {
                return ResourceManager.GetString("RegistryConfigCriticalTempThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskPoolProvider.
        /// </summary>
        internal static string RegistryConfigDiskPoolProvider {
            get {
                return ResourceManager.GetString("RegistryConfigDiskPoolProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableDebugLogging.
        /// </summary>
        internal static string RegistryConfigEnableDebugLogging {
            get {
                return ResourceManager.GetString("RegistryConfigEnableDebugLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FallbackToWmi.
        /// </summary>
        internal static string RegistryConfigFallbackToWmi {
            get {
                return ResourceManager.GetString("RegistryConfigFallbackToWmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy.
        /// </summary>
        internal static string RegistryConfigGpoFips {
            get {
                return ResourceManager.GetString("RegistryConfigGpoFips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Policies\Microsoft\FVE.
        /// </summary>
        internal static string RegistryConfigGpoFve {
            get {
                return ResourceManager.GetString("RegistryConfigGpoFve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Policies\Microsoft\FVE.
        /// </summary>
        internal static string RegistryConfigGpoFveCurrentControlSet {
            get {
                return ResourceManager.GetString("RegistryConfigGpoFveCurrentControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotTempThreshold.
        /// </summary>
        internal static string RegistryConfigHotTempThreshold {
            get {
                return ResourceManager.GetString("RegistryConfigHotTempThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IgnoreHot.
        /// </summary>
        internal static string RegistryConfigIgnoreHot {
            get {
                return ResourceManager.GetString("RegistryConfigIgnoreHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IgnoreVirtualDisks.
        /// </summary>
        internal static string RegistryConfigIgnoreVirtualDisks {
            get {
                return ResourceManager.GetString("RegistryConfigIgnoreVirtualDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IgnoreWarm.
        /// </summary>
        internal static string RegistryConfigIgnoreWarm {
            get {
                return ResourceManager.GetString("RegistryConfigIgnoreWarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEmailConfigValid.
        /// </summary>
        internal static string RegistryConfigIsEmailConfigValid {
            get {
                return ResourceManager.GetString("RegistryConfigIsEmailConfigValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseNmaNotificate.
        /// </summary>
        internal static string RegistryConfigIsNmaEnabled {
            get {
                return ResourceManager.GetString("RegistryConfigIsNmaEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseProwlNotificate.
        /// </summary>
        internal static string RegistryConfigIsProwlEnabled {
            get {
                return ResourceManager.GetString("RegistryConfigIsProwlEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartInspectDebugLogLocation.
        /// </summary>
        internal static string RegistryConfigLogLocation {
            get {
                return ResourceManager.GetString("RegistryConfigLogLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailAlertsEnabled.
        /// </summary>
        internal static string RegistryConfigMailAlertsEnabled {
            get {
                return ResourceManager.GetString("RegistryConfigMailAlertsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailPassword.
        /// </summary>
        internal static string RegistryConfigMailPassword {
            get {
                return ResourceManager.GetString("RegistryConfigMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailServer.
        /// </summary>
        internal static string RegistryConfigMailServer {
            get {
                return ResourceManager.GetString("RegistryConfigMailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailUser.
        /// </summary>
        internal static string RegistryConfigMailUser {
            get {
                return ResourceManager.GetString("RegistryConfigMailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NmaApiKeychain.
        /// </summary>
        internal static string RegistryConfigNmaApiKeychain {
            get {
                return ResourceManager.GetString("RegistryConfigNmaApiKeychain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverheatedTempThreshold.
        /// </summary>
        internal static string RegistryConfigOverheatedTempThreshold {
            get {
                return ResourceManager.GetString("RegistryConfigOverheatedTempThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PollingInterval.
        /// </summary>
        internal static string RegistryConfigPollingInterval {
            get {
                return ResourceManager.GetString("RegistryConfigPollingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreserveOnUninstall.
        /// </summary>
        internal static string RegistryConfigPreserveOnUninstall {
            get {
                return ResourceManager.GetString("RegistryConfigPreserveOnUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProwlApiKeychain.
        /// </summary>
        internal static string RegistryConfigProwlApiKeychain {
            get {
                return ResourceManager.GetString("RegistryConfigProwlApiKeychain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientEmail.
        /// </summary>
        internal static string RegistryConfigRecipientEmail {
            get {
                return ResourceManager.GetString("RegistryConfigRecipientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientEmail2.
        /// </summary>
        internal static string RegistryConfigRecipientEmail2 {
            get {
                return ResourceManager.GetString("RegistryConfigRecipientEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientEmail3.
        /// </summary>
        internal static string RegistryConfigRecipientEmail3 {
            get {
                return ResourceManager.GetString("RegistryConfigRecipientEmail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RecipientFriendly.
        /// </summary>
        internal static string RegistryConfigRecipientFriendly {
            get {
                return ResourceManager.GetString("RegistryConfigRecipientFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportCritical.
        /// </summary>
        internal static string RegistryConfigReportCritical {
            get {
                return ResourceManager.GetString("RegistryConfigReportCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportGeriatric.
        /// </summary>
        internal static string RegistryConfigReportGeriatric {
            get {
                return ResourceManager.GetString("RegistryConfigReportGeriatric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportWarning.
        /// </summary>
        internal static string RegistryConfigReportWarning {
            get {
                return ResourceManager.GetString("RegistryConfigReportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SenderEmail.
        /// </summary>
        internal static string RegistryConfigSenderEmail {
            get {
                return ResourceManager.GetString("RegistryConfigSenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SenderFriendly.
        /// </summary>
        internal static string RegistryConfigSenderFriendly {
            get {
                return ResourceManager.GetString("RegistryConfigSenderFriendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerPort.
        /// </summary>
        internal static string RegistryConfigServerPort {
            get {
                return ResourceManager.GetString("RegistryConfigServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Services\dnhsSmartFvePoolHelper.
        /// </summary>
        internal static string RegistryConfigServiceHelperKey {
            get {
                return ResourceManager.GetString("RegistryConfigServiceHelperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiIAdvanced.
        /// </summary>
        internal static string RegistryConfigSiIAdvanced {
            get {
                return ResourceManager.GetString("RegistryConfigSiIAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiIAdvanced.
        /// </summary>
        internal static string RegistryConfigSiIAdvanced1 {
            get {
                return ResourceManager.GetString("RegistryConfigSiIAdvanced1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdLifeLeftCritical.
        /// </summary>
        internal static string RegistryConfigSsdLifeLeftCritical {
            get {
                return ResourceManager.GetString("RegistryConfigSsdLifeLeftCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdLifeLeftCritical.
        /// </summary>
        internal static string RegistryConfigSsdLifeLeftCritical1 {
            get {
                return ResourceManager.GetString("RegistryConfigSsdLifeLeftCritical1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdLifeLeftWarning.
        /// </summary>
        internal static string RegistryConfigSsdLifeLeftWarning {
            get {
                return ResourceManager.GetString("RegistryConfigSsdLifeLeftWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdLifeLeftWarning.
        /// </summary>
        internal static string RegistryConfigSsdLifeLeftWarning1 {
            get {
                return ResourceManager.GetString("RegistryConfigSsdLifeLeftWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdRetirementCritical.
        /// </summary>
        internal static string RegistryConfigSsdRetirementCritical {
            get {
                return ResourceManager.GetString("RegistryConfigSsdRetirementCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdRetirementCritical.
        /// </summary>
        internal static string RegistryConfigSsdRetirementCritical1 {
            get {
                return ResourceManager.GetString("RegistryConfigSsdRetirementCritical1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdRetirementWarning.
        /// </summary>
        internal static string RegistryConfigSsdRetirementWarning {
            get {
                return ResourceManager.GetString("RegistryConfigSsdRetirementWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SsdRetirementWarning.
        /// </summary>
        internal static string RegistryConfigSsdRetirementWarning1 {
            get {
                return ResourceManager.GetString("RegistryConfigSsdRetirementWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemperaturePreference.
        /// </summary>
        internal static string RegistryConfigTemperaturePreference {
            get {
                return ResourceManager.GetString("RegistryConfigTemperaturePreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TemperaturePreference.
        /// </summary>
        internal static string RegistryConfigTemperaturePreference1 {
            get {
                return ResourceManager.GetString("RegistryConfigTemperaturePreference1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string RegistryConfigurationKey {
            get {
                return ResourceManager.GetString("RegistryConfigurationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string RegistryConfigurationKey1 {
            get {
                return ResourceManager.GetString("RegistryConfigurationKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoolHelperService.
        /// </summary>
        internal static string RegistryConfigurationPoolHelperKey {
            get {
                return ResourceManager.GetString("RegistryConfigurationPoolHelperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseDefaultSkinning.
        /// </summary>
        internal static string RegistryConfigUseDefaultSkinning {
            get {
                return ResourceManager.GetString("RegistryConfigUseDefaultSkinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseHelperService.
        /// </summary>
        internal static string RegistryConfigUseHelperService {
            get {
                return ResourceManager.GetString("RegistryConfigUseHelperService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseHelperService.
        /// </summary>
        internal static string RegistryConfigUseHelperService1 {
            get {
                return ResourceManager.GetString("RegistryConfigUseHelperService1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseSSL.
        /// </summary>
        internal static string RegistryConfigUseSSL {
            get {
                return ResourceManager.GetString("RegistryConfigUseSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseSSL.
        /// </summary>
        internal static string RegistryConfigUseSSL1 {
            get {
                return ResourceManager.GetString("RegistryConfigUseSSL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarmTempThreshold.
        /// </summary>
        internal static string RegistryConfigWarmTempThreshold {
            get {
                return ResourceManager.GetString("RegistryConfigWarmTempThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WarmTempThreshold.
        /// </summary>
        internal static string RegistryConfigWarmTempThreshold1 {
            get {
                return ResourceManager.GetString("RegistryConfigWarmTempThreshold1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowBackground.
        /// </summary>
        internal static string RegistryConfigWindowBackground {
            get {
                return ResourceManager.GetString("RegistryConfigWindowBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Dojo North Software\HomeServerSMART.
        /// </summary>
        internal static string RegistryDojoNorthRootKey {
            get {
                return ResourceManager.GetString("RegistryDojoNorthRootKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Dojo North Software\HomeServerSMART.
        /// </summary>
        internal static string RegistryDojoNorthRootKey1 {
            get {
                return ResourceManager.GetString("RegistryDojoNorthRootKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonitoredDisks.
        /// </summary>
        internal static string RegistryMonitoredDisksKey {
            get {
                return ResourceManager.GetString("RegistryMonitoredDisksKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonitoredDisks.
        /// </summary>
        internal static string RegistryMonitoredDisksKey1 {
            get {
                return ResourceManager.GetString("RegistryMonitoredDisksKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string RegistryServiceStartFlag {
            get {
                return ResourceManager.GetString("RegistryServiceStartFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like this Add-in?.
        /// </summary>
        internal static string ResourceDonationQuestion {
            get {
                return ResourceManager.GetString("ResourceDonationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat me to a Starbucks Frappuccino!.
        /// </summary>
        internal static string ResourceDonationText {
            get {
                return ResourceManager.GetString("ResourceDonationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=11344152.
        /// </summary>
        internal static string ResourceDonationUrl {
            get {
                return ResourceManager.GetString("ResourceDonationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.dojonorthsoftware.net/Freebies/HomeServerSMART2013.aspx.
        /// </summary>
        internal static string ResourceUrl {
            get {
                return ResourceManager.GetString("ResourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.pctechguide.com/hard-disks/hard-disk-smart-drives.
        /// </summary>
        internal static string ResourceUrlPcTechGuide {
            get {
                return ResourceManager.GetString("ResourceUrlPcTechGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Server SMART Homepage.
        /// </summary>
        internal static string ResourceUrlText {
            get {
                return ResourceManager.GetString("ResourceUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://en.wikipedia.org/wiki/S.M.A.R.T..
        /// </summary>
        internal static string ResourceUrlWikipedia {
            get {
                return ResourceManager.GetString("ResourceUrlWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Resume {
            get {
                object obj = ResourceManager.GetObject("Resume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap server_backup_16 {
            get {
                object obj = ResourceManager.GetObject("server_backup_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnhsSmart.
        /// </summary>
        internal static string ServiceNameHss {
            get {
                return ResourceManager.GetString("ServiceNameHss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnhsSmartFvePoolHelper.
        /// </summary>
        internal static string ServiceNameHssFveHelper {
            get {
                return ResourceManager.GetString("ServiceNameHssFveHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °C.
        /// </summary>
        internal static string SettingsDegreesC {
            get {
                return ResourceManager.GetString("SettingsDegreesC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  °F.
        /// </summary>
        internal static string SettingsDegreesF {
            get {
                return ResourceManager.GetString("SettingsDegreesF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  °K.
        /// </summary>
        internal static string SettingsDegreesK {
            get {
                return ResourceManager.GetString("SettingsDegreesK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SetupApi {
            get {
                object obj = ResourceManager.GetObject("SetupApi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldGreen16 {
            get {
                object obj = ResourceManager.GetObject("ShieldGreen16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldGreen24 {
            get {
                object obj = ResourceManager.GetObject("ShieldGreen24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldMulti16 {
            get {
                object obj = ResourceManager.GetObject("ShieldMulti16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldMulti24 {
            get {
                object obj = ResourceManager.GetObject("ShieldMulti24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldQuestion16 {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestion16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldQuestion24 {
            get {
                object obj = ResourceManager.GetObject("ShieldQuestion24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldRed16 {
            get {
                object obj = ResourceManager.GetObject("ShieldRed16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldRed24 {
            get {
                object obj = ResourceManager.GetObject("ShieldRed24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldYellow16 {
            get {
                object obj = ResourceManager.GetObject("ShieldYellow16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldYellow24 {
            get {
                object obj = ResourceManager.GetObject("ShieldYellow24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShutDown16 {
            get {
                object obj = ResourceManager.GetObject("ShutDown16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Starbux {
            get {
                object obj = ResourceManager.GetObject("Starbux", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap status_warning_16 {
            get {
                object obj = ResourceManager.GetObject("status_warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stopwatch_with_Arrows {
            get {
                object obj = ResourceManager.GetObject("Stopwatch_with_Arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Subtract {
            get {
                object obj = ResourceManager.GetObject("Subtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unlock16 {
            get {
                object obj = ResourceManager.GetObject("Unlock16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unlock24 {
            get {
                object obj = ResourceManager.GetObject("Unlock24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Updates16 {
            get {
                object obj = ResourceManager.GetObject("Updates16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warning16 {
            get {
                object obj = ResourceManager.GetObject("Warning16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string WindowTitleConfirm {
            get {
                return ResourceManager.GetString("WindowTitleConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WindowTitleWarning {
            get {
                return ResourceManager.GetString("WindowTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Win32_DiskDrive.
        /// </summary>
        internal static string WmiQueryStringNonWin8 {
            get {
                return ResourceManager.GetString("WmiQueryStringNonWin8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from MSFT_PhysicalDisk.
        /// </summary>
        internal static string WmiQueryStringWin8 {
            get {
                return ResourceManager.GetString("WmiQueryStringWin8", resourceCulture);
            }
        }
    }
}
