//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.WindowSMARTTray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.WindowSMARTTray.Prop" +
                            "erties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activeAlerts.xml.
        /// </summary>
        internal static string ActiveAlertsXml {
            get {
                return ResourceManager.GetString("ActiveAlertsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationEventLog {
            get {
                return ResourceManager.GetString("ApplicationEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSMART 24/7.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2012 Dojo North Software, LLC.
        /// </summary>
        internal static string CopyrightBanner {
            get {
                return ResourceManager.GetString("CopyrightBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Windows Server\Bin\Dashboard.exe.
        /// </summary>
        internal static string DashboardLocation {
            get {
                return ResourceManager.GetString("DashboardLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated in Memory of Joseph B. Sawyer.
        /// </summary>
        internal static string DedicationBanner {
            get {
                return ResourceManager.GetString("DedicationBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DiskHeartBeat16 {
            get {
                object obj = ResourceManager.GetObject("DiskHeartBeat16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DiskHeartBeat16Red {
            get {
                object obj = ResourceManager.GetObject("DiskHeartBeat16Red", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DiskHeartBeat16Yellow {
            get {
                object obj = ResourceManager.GetObject("DiskHeartBeat16Yellow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSMART-E.
        /// </summary>
        internal static string EventLogJoshua {
            get {
                return ResourceManager.GetString("EventLogJoshua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSMART-W.
        /// </summary>
        internal static string EventLogTaryn {
            get {
                return ResourceManager.GetString("EventLogTaryn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HunkaHunkaMcBabyMcOrneryMcSlabMcHandsomeMcBabyMcGoodLookingMcSlabMcFlawlessMcSlabMcBaby {
            get {
                object obj = ResourceManager.GetObject("HunkaHunkaMcBabyMcOrneryMcSlabMcHandsomeMcBabyMcGoodLookingMcSlabMcFlawlessMcSlab" +
                        "McBaby", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon JoshGoodLooking {
            get {
                object obj = ResourceManager.GetObject("JoshGoodLooking", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sil.
        /// </summary>
        internal static string LogfileExtension {
            get {
                return ResourceManager.GetString("LogfileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSmartTrayLog_.
        /// </summary>
        internal static string LogfilePrefix {
            get {
                return ResourceManager.GetString("LogfilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QtuueAPfySA3unmcnlJBUlr4HECiNamD7PitXdrG56AIg6iEQIYLtiRbEqBT4dwTCfxP1rXlVm4ROoS7DrzF0+mDdHbveilZ/ArGQn2azqW3++0PvdKtoZgvMaLPUWs2eG2ppZP2vcwDkWMBua3cdLi01snaDQppti51ADMORPDNscx3.
        /// </summary>
        internal static string RegistryConfigCriticalFailure {
            get {
                return ResourceManager.GetString("RegistryConfigCriticalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseGrowlNotificate.
        /// </summary>
        internal static string RegistryConfigIsGrowlEnabled {
            get {
                return ResourceManager.GetString("RegistryConfigIsGrowlEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseGrowlRemoteNotificate.
        /// </summary>
        internal static string RegistryConfigIsGrowlRemoteEnabled {
            get {
                return ResourceManager.GetString("RegistryConfigIsGrowlRemoteEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseSnarlNotificate.
        /// </summary>
        internal static string RegistryConfigIsSnarlEnabled {
            get {
                return ResourceManager.GetString("RegistryConfigIsSnarlEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string RegistryConfigurationKey {
            get {
                return ResourceManager.GetString("RegistryConfigurationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Dojo North Software\HomeServerSMART.
        /// </summary>
        internal static string RegistryDojoNorthRootKey {
            get {
                return ResourceManager.GetString("RegistryDojoNorthRootKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnhsSmart.
        /// </summary>
        internal static string ServiceNameHss {
            get {
                return ResourceManager.GetString("ServiceNameHss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShieldMulti16 {
            get {
                object obj = ResourceManager.GetObject("ShieldMulti16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SkullAndCrossbonesRed32 {
            get {
                object obj = ResourceManager.GetObject("SkullAndCrossbonesRed32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Unknown16 {
            get {
                object obj = ResourceManager.GetObject("Unknown16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
