//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojoNorthSoftware.WindowSMART.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DojoNorthSoftware.WindowSMART.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JBUlr4HECiNamD7PitXdrG56AIg6iEQIYLtiRbEqBT4dwTCfxP1rXlVm4ROoS7DrzF0+mDdHbveilZ/ArGQn2azqW3++0PvdKtoZgvMaLPUWs2eG2ppZP2vcwDkWMBua3cdLi01snaDQppti51ADMORPDNscx3.
        /// </summary>
        internal static string RegistryConfigHelperServiceKey {
            get {
                return ResourceManager.GetString("RegistryConfigHelperServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QtuueAPfySA3unmcnlJBUlr4HECiNamD7PitXdrG56AIg6iEQIYLtiRbEqBT4dwTCfxP1rXlVm4ROoS7DrzF0+mDdHbveilZ/ArGQn2azqW3++0PvdKtoZgvMaLPUWs2eG2ppZP2vcwDkWMBua3cdLi01snaDQppti51ADMORPDNscx3.
        /// </summary>
        internal static string RegistryConfigPowerShell {
            get {
                return ResourceManager.GetString("RegistryConfigPowerShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnhsSmart.
        /// </summary>
        internal static string ServiceNameHss {
            get {
                return ResourceManager.GetString("ServiceNameHss", resourceCulture);
            }
        }
    }
}
