//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.Service.Properties.R" +
                            "esources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveBender.
        /// </summary>
        internal static string DiskPoolProviderDriveBender {
            get {
                return ResourceManager.GetString("DiskPoolProviderDriveBender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StableBitDrivePool.
        /// </summary>
        internal static string DiskPoolProviderDrivePool {
            get {
                return ResourceManager.GetString("DiskPoolProviderDrivePool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSMART-E.
        /// </summary>
        internal static string EventLogJoshua {
            get {
                return ResourceManager.GetString("EventLogJoshua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowSMART-W.
        /// </summary>
        internal static string EventLogTaryn {
            get {
                return ResourceManager.GetString("EventLogTaryn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .sil.
        /// </summary>
        internal static string LogfileExtension {
            get {
                return ResourceManager.GetString("LogfileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HssSvcLog_.
        /// </summary>
        internal static string LogfilePrefix {
            get {
                return ResourceManager.GetString("LogfilePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiskPoolProvider.
        /// </summary>
        internal static string RegistryConfigDiskPoolProvider {
            get {
                return ResourceManager.GetString("RegistryConfigDiskPoolProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JBUlr4HECiNamD7PitXdrG56AIg6iEQIYLtiRbEqBT4dwTCfxP1rXlVm4ROoS7DrzF0+mDdHbveilZ/ArGQn2azqW3++0PvdKtoZgvMaLPUWs2eG2ppZP2vcwDkWMBua3cdLi01snaDQppti51ADMORPDNscx3.
        /// </summary>
        internal static string RegistryConfigHelperServiceKey {
            get {
                return ResourceManager.GetString("RegistryConfigHelperServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartInspectDebugLogLocation.
        /// </summary>
        internal static string RegistryConfigLogLocation {
            get {
                return ResourceManager.GetString("RegistryConfigLogLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Services\dnhsSmartFvePoolHelper.
        /// </summary>
        internal static string RegistryConfigServiceHelperKey {
            get {
                return ResourceManager.GetString("RegistryConfigServiceHelperKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Services.
        /// </summary>
        internal static string RegistryConfigServiceRootKey {
            get {
                return ResourceManager.GetString("RegistryConfigServiceRootKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string RegistryConfigurationKey {
            get {
                return ResourceManager.GetString("RegistryConfigurationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoolHelperService.
        /// </summary>
        internal static string RegistryConfigurationPoolHelper {
            get {
                return ResourceManager.GetString("RegistryConfigurationPoolHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseDefaultSkinning.
        /// </summary>
        internal static string RegistryConfigUseDefaultSkinning {
            get {
                return ResourceManager.GetString("RegistryConfigUseDefaultSkinning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseHelperService.
        /// </summary>
        internal static string RegistryConfigUseHelperService {
            get {
                return ResourceManager.GetString("RegistryConfigUseHelperService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Dojo North Software\HomeServerSMART.
        /// </summary>
        internal static string RegistryDojoNorthRootKey {
            get {
                return ResourceManager.GetString("RegistryDojoNorthRootKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MonitoredDisks.
        /// </summary>
        internal static string RegistryMonitoredDisksKey {
            get {
                return ResourceManager.GetString("RegistryMonitoredDisksKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string RegistryServiceStartFlag {
            get {
                return ResourceManager.GetString("RegistryServiceStartFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnhsSmart.
        /// </summary>
        internal static string ServiceNameHss {
            get {
                return ResourceManager.GetString("ServiceNameHss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnhsSmartFvePoolHelper.
        /// </summary>
        internal static string ServiceNameHssFveHelper {
            get {
                return ResourceManager.GetString("ServiceNameHssFveHelper", resourceCulture);
            }
        }
    }
}
