//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.Components.HssUpdate {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HssUpdateSoap", Namespace="http://www.dojonorthsoftware.net/")]
    public partial class HssUpdate : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReapVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReapReleaseDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReapDownloadLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReapInfoLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReapHs2VersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReapHs2ReleaseDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReapHs2DownloadLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReapHs2InfoLinkOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompareVersionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HssUpdate() {
            this.Url = global::DojoNorthSoftware.WindowsServerSolutions.HomeServerSMART2013.Components.Properties.Settings.Default.HomeServerConsoleTab_HomeServerSMART_HssUpdate_HssUpdate;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReapVersionCompletedEventHandler ReapVersionCompleted;
        
        /// <remarks/>
        public event ReapReleaseDateCompletedEventHandler ReapReleaseDateCompleted;
        
        /// <remarks/>
        public event ReapDownloadLinkCompletedEventHandler ReapDownloadLinkCompleted;
        
        /// <remarks/>
        public event ReapInfoLinkCompletedEventHandler ReapInfoLinkCompleted;
        
        /// <remarks/>
        public event ReapHs2VersionCompletedEventHandler ReapHs2VersionCompleted;
        
        /// <remarks/>
        public event ReapHs2ReleaseDateCompletedEventHandler ReapHs2ReleaseDateCompleted;
        
        /// <remarks/>
        public event ReapHs2DownloadLinkCompletedEventHandler ReapHs2DownloadLinkCompleted;
        
        /// <remarks/>
        public event ReapHs2InfoLinkCompletedEventHandler ReapHs2InfoLinkCompleted;
        
        /// <remarks/>
        public event CompareVersionCompletedEventHandler CompareVersionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapVersion", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapVersion() {
            object[] results = this.Invoke("ReapVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapVersionAsync() {
            this.ReapVersionAsync(null);
        }
        
        /// <remarks/>
        public void ReapVersionAsync(object userState) {
            if ((this.ReapVersionOperationCompleted == null)) {
                this.ReapVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapVersionOperationCompleted);
            }
            this.InvokeAsync("ReapVersion", new object[0], this.ReapVersionOperationCompleted, userState);
        }
        
        private void OnReapVersionOperationCompleted(object arg) {
            if ((this.ReapVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapVersionCompleted(this, new ReapVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapReleaseDate", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapReleaseDate() {
            object[] results = this.Invoke("ReapReleaseDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapReleaseDateAsync() {
            this.ReapReleaseDateAsync(null);
        }
        
        /// <remarks/>
        public void ReapReleaseDateAsync(object userState) {
            if ((this.ReapReleaseDateOperationCompleted == null)) {
                this.ReapReleaseDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapReleaseDateOperationCompleted);
            }
            this.InvokeAsync("ReapReleaseDate", new object[0], this.ReapReleaseDateOperationCompleted, userState);
        }
        
        private void OnReapReleaseDateOperationCompleted(object arg) {
            if ((this.ReapReleaseDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapReleaseDateCompleted(this, new ReapReleaseDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapDownloadLink", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapDownloadLink() {
            object[] results = this.Invoke("ReapDownloadLink", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapDownloadLinkAsync() {
            this.ReapDownloadLinkAsync(null);
        }
        
        /// <remarks/>
        public void ReapDownloadLinkAsync(object userState) {
            if ((this.ReapDownloadLinkOperationCompleted == null)) {
                this.ReapDownloadLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapDownloadLinkOperationCompleted);
            }
            this.InvokeAsync("ReapDownloadLink", new object[0], this.ReapDownloadLinkOperationCompleted, userState);
        }
        
        private void OnReapDownloadLinkOperationCompleted(object arg) {
            if ((this.ReapDownloadLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapDownloadLinkCompleted(this, new ReapDownloadLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapInfoLink", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapInfoLink() {
            object[] results = this.Invoke("ReapInfoLink", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapInfoLinkAsync() {
            this.ReapInfoLinkAsync(null);
        }
        
        /// <remarks/>
        public void ReapInfoLinkAsync(object userState) {
            if ((this.ReapInfoLinkOperationCompleted == null)) {
                this.ReapInfoLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapInfoLinkOperationCompleted);
            }
            this.InvokeAsync("ReapInfoLink", new object[0], this.ReapInfoLinkOperationCompleted, userState);
        }
        
        private void OnReapInfoLinkOperationCompleted(object arg) {
            if ((this.ReapInfoLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapInfoLinkCompleted(this, new ReapInfoLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapHs2Version", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapHs2Version() {
            object[] results = this.Invoke("ReapHs2Version", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapHs2VersionAsync() {
            this.ReapHs2VersionAsync(null);
        }
        
        /// <remarks/>
        public void ReapHs2VersionAsync(object userState) {
            if ((this.ReapHs2VersionOperationCompleted == null)) {
                this.ReapHs2VersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapHs2VersionOperationCompleted);
            }
            this.InvokeAsync("ReapHs2Version", new object[0], this.ReapHs2VersionOperationCompleted, userState);
        }
        
        private void OnReapHs2VersionOperationCompleted(object arg) {
            if ((this.ReapHs2VersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapHs2VersionCompleted(this, new ReapHs2VersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapHs2ReleaseDate", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapHs2ReleaseDate() {
            object[] results = this.Invoke("ReapHs2ReleaseDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapHs2ReleaseDateAsync() {
            this.ReapHs2ReleaseDateAsync(null);
        }
        
        /// <remarks/>
        public void ReapHs2ReleaseDateAsync(object userState) {
            if ((this.ReapHs2ReleaseDateOperationCompleted == null)) {
                this.ReapHs2ReleaseDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapHs2ReleaseDateOperationCompleted);
            }
            this.InvokeAsync("ReapHs2ReleaseDate", new object[0], this.ReapHs2ReleaseDateOperationCompleted, userState);
        }
        
        private void OnReapHs2ReleaseDateOperationCompleted(object arg) {
            if ((this.ReapHs2ReleaseDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapHs2ReleaseDateCompleted(this, new ReapHs2ReleaseDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapHs2DownloadLink", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapHs2DownloadLink() {
            object[] results = this.Invoke("ReapHs2DownloadLink", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapHs2DownloadLinkAsync() {
            this.ReapHs2DownloadLinkAsync(null);
        }
        
        /// <remarks/>
        public void ReapHs2DownloadLinkAsync(object userState) {
            if ((this.ReapHs2DownloadLinkOperationCompleted == null)) {
                this.ReapHs2DownloadLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapHs2DownloadLinkOperationCompleted);
            }
            this.InvokeAsync("ReapHs2DownloadLink", new object[0], this.ReapHs2DownloadLinkOperationCompleted, userState);
        }
        
        private void OnReapHs2DownloadLinkOperationCompleted(object arg) {
            if ((this.ReapHs2DownloadLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapHs2DownloadLinkCompleted(this, new ReapHs2DownloadLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/ReapHs2InfoLink", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReapHs2InfoLink() {
            object[] results = this.Invoke("ReapHs2InfoLink", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReapHs2InfoLinkAsync() {
            this.ReapHs2InfoLinkAsync(null);
        }
        
        /// <remarks/>
        public void ReapHs2InfoLinkAsync(object userState) {
            if ((this.ReapHs2InfoLinkOperationCompleted == null)) {
                this.ReapHs2InfoLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReapHs2InfoLinkOperationCompleted);
            }
            this.InvokeAsync("ReapHs2InfoLink", new object[0], this.ReapHs2InfoLinkOperationCompleted, userState);
        }
        
        private void OnReapHs2InfoLinkOperationCompleted(object arg) {
            if ((this.ReapHs2InfoLinkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReapHs2InfoLinkCompleted(this, new ReapHs2InfoLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.dojonorthsoftware.net/CompareVersion", RequestNamespace="http://www.dojonorthsoftware.net/", ResponseNamespace="http://www.dojonorthsoftware.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CompareVersion(string major, string minor, string meta) {
            object[] results = this.Invoke("CompareVersion", new object[] {
                        major,
                        minor,
                        meta});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CompareVersionAsync(string major, string minor, string meta) {
            this.CompareVersionAsync(major, minor, meta, null);
        }
        
        /// <remarks/>
        public void CompareVersionAsync(string major, string minor, string meta, object userState) {
            if ((this.CompareVersionOperationCompleted == null)) {
                this.CompareVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompareVersionOperationCompleted);
            }
            this.InvokeAsync("CompareVersion", new object[] {
                        major,
                        minor,
                        meta}, this.CompareVersionOperationCompleted, userState);
        }
        
        private void OnCompareVersionOperationCompleted(object arg) {
            if ((this.CompareVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompareVersionCompleted(this, new CompareVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapVersionCompletedEventHandler(object sender, ReapVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapReleaseDateCompletedEventHandler(object sender, ReapReleaseDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapReleaseDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapReleaseDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapDownloadLinkCompletedEventHandler(object sender, ReapDownloadLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapDownloadLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapDownloadLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapInfoLinkCompletedEventHandler(object sender, ReapInfoLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapInfoLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapInfoLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapHs2VersionCompletedEventHandler(object sender, ReapHs2VersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapHs2VersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapHs2VersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapHs2ReleaseDateCompletedEventHandler(object sender, ReapHs2ReleaseDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapHs2ReleaseDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapHs2ReleaseDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapHs2DownloadLinkCompletedEventHandler(object sender, ReapHs2DownloadLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapHs2DownloadLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapHs2DownloadLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ReapHs2InfoLinkCompletedEventHandler(object sender, ReapHs2InfoLinkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReapHs2InfoLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReapHs2InfoLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void CompareVersionCompletedEventHandler(object sender, CompareVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompareVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompareVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591