//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowSMARTEnterpriseManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowSMARTEnterpriseManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupportMessage.
        /// </summary>
        internal static string RegistryConfigCustomSupportMessage {
            get {
                return ResourceManager.GetString("RegistryConfigCustomSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvancedSettings.
        /// </summary>
        internal static string RegistryConfigGpoAdvancedSettings {
            get {
                return ResourceManager.GetString("RegistryConfigGpoAdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowIgnoredItems.
        /// </summary>
        internal static string RegistryConfigGpoAllowIgnoredItems {
            get {
                return ResourceManager.GetString("RegistryConfigGpoAllowIgnoredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowServiceControl.
        /// </summary>
        internal static string RegistryConfigGpoAllowServiceControl {
            get {
                return ResourceManager.GetString("RegistryConfigGpoAllowServiceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowShutdownReboot.
        /// </summary>
        internal static string RegistryConfigGpoAllowShutdownReboot {
            get {
                return ResourceManager.GetString("RegistryConfigGpoAllowShutdownReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInterfaceMode.
        /// </summary>
        internal static string RegistryConfigGpoBlockUi {
            get {
                return ResourceManager.GetString("RegistryConfigGpoBlockUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoxcarNotificate.
        /// </summary>
        internal static string RegistryConfigGpoBoxcarNotificate {
            get {
                return ResourceManager.GetString("RegistryConfigGpoBoxcarNotificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckForUpdates.
        /// </summary>
        internal static string RegistryConfigGpoCheckForUpdates {
            get {
                return ResourceManager.GetString("RegistryConfigGpoCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebuggingControl.
        /// </summary>
        internal static string RegistryConfigGpoDebuggingControl {
            get {
                return ResourceManager.GetString("RegistryConfigGpoDebuggingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteStale.
        /// </summary>
        internal static string RegistryConfigGpoDeleteStale {
            get {
                return ResourceManager.GetString("RegistryConfigGpoDeleteStale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dpa.
        /// </summary>
        internal static string RegistryConfigGpoDpa {
            get {
                return ResourceManager.GetString("RegistryConfigGpoDpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailNotificate.
        /// </summary>
        internal static string RegistryConfigGpoEmailNotificate {
            get {
                return ResourceManager.GetString("RegistryConfigGpoEmailNotificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseEmergencyBackup.
        /// </summary>
        internal static string RegistryConfigGpoEmergencyBackup {
            get {
                return ResourceManager.GetString("RegistryConfigGpoEmergencyBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy.
        /// </summary>
        internal static string RegistryConfigGpoFips {
            get {
                return ResourceManager.GetString("RegistryConfigGpoFips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Policies\Microsoft\FVE.
        /// </summary>
        internal static string RegistryConfigGpoFve {
            get {
                return ResourceManager.GetString("RegistryConfigGpoFve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Policies\Microsoft\FVE.
        /// </summary>
        internal static string RegistryConfigGpoFveCurrentControlSet {
            get {
                return ResourceManager.GetString("RegistryConfigGpoFveCurrentControlSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrowlNotificate.
        /// </summary>
        internal static string RegistryConfigGpoGrowlNotificate {
            get {
                return ResourceManager.GetString("RegistryConfigGpoGrowlNotificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NmaNotificate.
        /// </summary>
        internal static string RegistryConfigGpoNmaNotificate {
            get {
                return ResourceManager.GetString("RegistryConfigGpoNmaNotificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProwlNotificate.
        /// </summary>
        internal static string RegistryConfigGpoProwlNotificate {
            get {
                return ResourceManager.GetString("RegistryConfigGpoProwlNotificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetEverything.
        /// </summary>
        internal static string RegistryConfigGpoResetEverything {
            get {
                return ResourceManager.GetString("RegistryConfigGpoResetEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestoreDefaults.
        /// </summary>
        internal static string RegistryConfigGpoRestoreDefaults {
            get {
                return ResourceManager.GetString("RegistryConfigGpoRestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SnarlNotificate.
        /// </summary>
        internal static string RegistryConfigGpoSnarlNotificate {
            get {
                return ResourceManager.GetString("RegistryConfigGpoSnarlNotificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSD.
        /// </summary>
        internal static string RegistryConfigGpoSSD {
            get {
                return ResourceManager.GetString("RegistryConfigGpoSSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempCtl.
        /// </summary>
        internal static string RegistryConfigGpoTempCtl {
            get {
                return ResourceManager.GetString("RegistryConfigGpoTempCtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UiTheme.
        /// </summary>
        internal static string RegistryConfigGpoUiTheme {
            get {
                return ResourceManager.GetString("RegistryConfigGpoUiTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseSupportMessage.
        /// </summary>
        internal static string RegistryConfigGpoUseSupportMessage {
            get {
                return ResourceManager.GetString("RegistryConfigGpoUseSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VirtualIgnore.
        /// </summary>
        internal static string RegistryConfigGpoVirtualIgnore {
            get {
                return ResourceManager.GetString("RegistryConfigGpoVirtualIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowsPhoneNotificate.
        /// </summary>
        internal static string RegistryConfigGpoWindowsPhoneNotificate {
            get {
                return ResourceManager.GetString("RegistryConfigGpoWindowsPhoneNotificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogRequirement.
        /// </summary>
        internal static string RegistryConfigLogRequirement {
            get {
                return ResourceManager.GetString("RegistryConfigLogRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string RegistryConfigurationKey {
            get {
                return ResourceManager.GetString("RegistryConfigurationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Dojo North Software\HomeServerSMART.
        /// </summary>
        internal static string RegistryDojoNorthRootKey {
            get {
                return ResourceManager.GetString("RegistryDojoNorthRootKey", resourceCulture);
            }
        }
    }
}
